/* My keymap */
#define KEYMAP 1

/* Themes */
// Default
#define DEFAULT 1
// GRUVBOX 
#define GRUVBOX_DARK 0
#define GRUVBOX_MEDIUM 0
#define GRUVBOX_LIGHT 0

/* ATTACHDIR */
#define ATTACHABOVE_PATCH 0
#define ATTACHASIDE_PATCH 0
#define ATTACHBELOW_PATCH 1
#define ATTACHBOTTOM_PATCH 0
#define ATTACHASIDEBELOW_PATCH 0
